import {firebaseConfig,firebaseConfigured} from './firebase-config.js?v=3.0.1';
const SDK='12.18.0';
const META_KEY='pf_cloud_meta_v1',OPT_KEY='pf_cloud_opt_in_v1',CLIENT_KEY='pf_cloud_client_v1';
const SYNC_MS=90*60*1000,MAX_PAYLOAD_CHARS=880000;
let sdk=null,app=null,auth=null,db=null,user=null,busy=false,interval=null,lastCloudDoc=null;
const $=s=>document.querySelector(s), bridge=()=>window.PackForgeBridge;
function clientId(){let v=localStorage.getItem(CLIENT_KEY);if(!v){v=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`);localStorage.setItem(CLIENT_KEY,v)}return v}
function meta(){try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch(e){return{}}}
function setMeta(v){localStorage.setItem(META_KEY,JSON.stringify({...meta(),...v}))}
function status(msg,kind=''){const e=$('#pfCloudStatus');if(e){e.textContent=msg;e.className='pf-cloud-status '+kind}}
function setUserUI(){const box=$('#pfCloudUser'),sign=$('#pfCloudSignIn'),out=$('#pfCloudSignOut'),sync=$('#pfCloudSync'),use=$('#pfCloudUse'),upload=$('#pfCloudUpload');if(!box)return;if(user){box.classList.remove('hidden');const av=$('#pfCloudAvatar'),nm=$('#pfCloudName'),sub=$('#pfCloudSub');if(av)av.innerHTML=user.photoURL?`<img alt="" src="${user.photoURL}">`:'G';if(nm)nm.textContent=user.displayName||'Google Player';if(sub)sub.textContent='Cloud save linked';sign?.classList.add('hidden');out?.classList.remove('hidden');sync?.classList.remove('hidden');upload?.classList.remove('hidden')}else{box.classList.add('hidden');sign?.classList.remove('hidden');out?.classList.add('hidden');sync?.classList.add('hidden');use?.classList.add('hidden');upload?.classList.add('hidden')}}
async function loadSdk(){if(sdk)return sdk;if(!firebaseConfigured)throw new Error('Firebase is not configured yet.');const [a,au,fs]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${SDK}/firebase-firestore.js`)]);sdk={...a,...au,...fs};app=sdk.getApps().length?sdk.getApp():sdk.initializeApp(firebaseConfig);auth=sdk.getAuth(app);db=sdk.getFirestore(app);await sdk.setPersistence(auth,sdk.browserLocalPersistence);return sdk}
async function gzipBase64(text){if(!('CompressionStream'in window))return {encoding:'json',payload:text};const cs=new CompressionStream('gzip'),writer=cs.writable.getWriter();writer.write(new TextEncoder().encode(text));writer.close();const buf=await new Response(cs.readable).arrayBuffer();let bin='';const u=new Uint8Array(buf),step=0x8000;for(let i=0;i<u.length;i+=step)bin+=String.fromCharCode(...u.subarray(i,i+step));return {encoding:'gzip-base64',payload:btoa(bin)}}
async function decodePayload(doc){if(doc.encoding!=='gzip-base64')return JSON.parse(doc.payload);if(!('DecompressionStream'in window))throw new Error('This browser cannot decompress the cloud save. Use a current Chrome/Edge/Safari build.');const bin=atob(doc.payload),u=Uint8Array.from(bin,c=>c.charCodeAt(0)),ds=new DecompressionStream('gzip'),writer=ds.writable.getWriter();writer.write(u);writer.close();return JSON.parse(await new Response(ds.readable).text())}
async function hashText(t){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function meaningful(s){return (Number(s?.stats?.clicks)||0)+(Number(s?.packsOpened)||0)*10+(Object.keys(s?.inventory||{}).length)>10}
async function localEncoded(){const snap=bridge()?.getSnapshot?.();if(!snap)throw new Error('PackForge save bridge is not ready.');const raw=JSON.stringify(snap),hash=await hashText(raw),enc=await gzipBase64(raw);if(enc.payload.length>MAX_PAYLOAD_CHARS)throw new Error('Your compressed save is too large for the single cloud slot. Export a local backup before continuing.');return {snap,hash,...enc}}
function saveRef(){return sdk.doc(db,'users',user.uid,'saves','main')} function metaRef(){return sdk.doc(db,'users',user.uid,'saveMeta','main')}
async function fetchCloudMeta(){const ss=await sdk.getDoc(metaRef());return ss.exists()?{id:ss.id,...ss.data()}:null} async function fetchCloudPayload(){const ss=await sdk.getDoc(saveRef());return ss.exists()?{id:ss.id,...ss.data()}:null}
async function upload({force=false}={}){if(!user||busy)return false;busy=true;status('Checking cloud revision…');try{const local=await localEncoded(),m=meta(),mref=metaRef(),pref=saveRef(),now=Date.now();let newRevision=1;await sdk.runTransaction(db,async tx=>{const ss=await tx.get(mref),remote=ss.exists()?ss.data():null;if(remote){newRevision=(Number(remote.revision)||0)+1;const changedElsewhere=(Number(remote.revision)||0)!==(Number(m.revision)||0)&&remote.clientId!==clientId();if(changedElsewhere&&!force){const err=new Error('Cloud save changed on another device.');err.code='PF_CONFLICT';throw err}}const common={schemaVersion:bridge()?.schemaVersion?.()||local.snap.schemaVersion||1,revision:newRevision,updatedAtMs:now,clientId:clientId(),payloadHash:local.hash};tx.set(mref,{...common,displayName:(user.displayName||'Player').slice(0,32)},{merge:false});tx.set(pref,{...common,encoding:local.encoding,payload:local.payload},{merge:false})});setMeta({revision:newRevision,lastHash:local.hash,lastSyncAt:now});lastCloudDoc={revision:newRevision,payloadHash:local.hash,updatedAtMs:now,clientId:clientId()};status(`Synced to Google · revision ${newRevision}`,'good');$('#pfCloudUse')?.classList.add('hidden');return true}catch(e){console.warn(e);if(e.code==='PF_CONFLICT'){status('Another device has a different cloud revision. Choose Use Cloud Save or Upload This Device.','warn');$('#pfCloudUse')?.classList.remove('hidden')}else status(e.message||'Cloud sync failed.','bad');return false}finally{busy=false}}
async function loadCloudIntoGame(){if(!user||busy)return;busy=true;status('Downloading cloud save…');try{let d=await fetchCloudPayload();if(!d)throw new Error('No cloud save exists for this Google account yet.');const m=lastCloudDoc||await fetchCloudMeta();if(m&&Number(d.revision)!==Number(m.revision)){await new Promise(r=>setTimeout(r,350));d=await fetchCloudPayload()}if(m&&Number(d.revision)!==Number(m.revision))throw new Error('Cloud save is between revisions. Try again in a moment.');const obj=await decodePayload(d);bridge()?.backupCurrent?.();setMeta({revision:Number(d.revision)||0,lastHash:d.payloadHash||'',lastSyncAt:Date.now()});status('Cloud save loaded. Reloading…','good');bridge()?.replaceSaveAndReload?.(obj,'google-cloud')}catch(e){status(e.message||'Could not load cloud save.','bad')}finally{busy=false}}
async function reconcile(){const d=await fetchCloudMeta();lastCloudDoc=d;const local=await localEncoded();if(!d){status('No cloud save yet — uploading this device.');return upload({force:true})}setMeta({revision:Number(d.revision)||0});if(d.payloadHash&&d.payloadHash===local.hash){setMeta({lastHash:local.hash,lastSyncAt:Date.now()});status('Local and Google cloud saves match.','good');return true}const s=bridge()?.getState?.();if(!meaningful(s)){status('Restoring your Google cloud save…');return loadCloudIntoGame()}status('This device and Google have different progress. Choose which copy you want to keep.','warn');$('#pfCloudUse')?.classList.remove('hidden');return false}
async function signIn(){if(!firebaseConfigured){status('Firebase config is still a placeholder. Send me the Firebase Web App config and I can wire it in.','warn');return}try{await loadSdk();localStorage.setItem(OPT_KEY,'1');const provider=new sdk.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});user=(await sdk.signInWithPopup(auth,provider)).user;setUserUI();status(`Signed in as ${user.displayName||'Google Player'}. Checking saves…`);await reconcile();startInterval()}catch(e){console.warn(e);status(e.message||'Google sign-in failed.','bad')}}
async function signOut(){try{await loadSdk();await sdk.signOut(auth)}catch(e){}user=null;localStorage.removeItem(OPT_KEY);setUserUI();status('Playing locally as guest.');if(interval){clearInterval(interval);interval=null}}
async function syncIfDirty(){if(!user||document.hidden||busy)return;const local=await localEncoded(),m=meta();if(local.hash===m.lastHash){status('Cloud save is already current.','good');return}await upload()}
function startInterval(){if(interval)clearInterval(interval);interval=setInterval(()=>{if(!document.hidden)syncIfDirty()},SYNC_MS)}
function bind(){setUserUI();$('#pfCloudSignIn')?.addEventListener('click',signIn);$('#pfCloudSignOut')?.addEventListener('click',signOut);$('#pfCloudSync')?.addEventListener('click',syncIfDirty);$('#pfCloudUse')?.addEventListener('click',()=>{if(confirm('Replace this device with the Google cloud save? A local recovery snapshot will be attempted first.'))loadCloudIntoGame()});$('#pfCloudUpload')?.addEventListener('click',()=>{if(confirm('Upload this device and overwrite the current Google cloud save? Use this only when this device has the progress you want to keep.'))upload({force:true})});if(!firebaseConfigured){status('Cloud-save code is installed, but Firebase still needs your Web App configuration. Local play is unaffected.','warn');return}if(localStorage.getItem(OPT_KEY)==='1')restoreSession()}
async function restoreSession(){try{await loadSdk();sdk.onAuthStateChanged(auth,async u=>{user=u;setUserUI();if(u){status(`Signed in as ${u.displayName||'Google Player'}.`);await reconcile();startInterval()}else status('Playing locally as guest.')})}catch(e){status(e.message||'Could not initialize cloud save.','bad')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
